# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: bak

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: bak
    main: .
    binary: bak
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/danielxxomg/bak-cli/cmd.Version={{.Version}}
      - -X github.com/danielxxomg/bak-cli/cmd.Commit={{.Commit}}
      - -X github.com/danielxxomg/bak-cli/cmd.Date={{.Date}}

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
