// Package backup implements the backup engine, secret scanning,
// and the integration points that wire adapters to CLI commands.
package backup

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/danielxxomg/bak-cli/internal/paths"
)

// DefaultPatterns returns the built-in set of regex patterns used to
// detect secrets (API keys, tokens, passwords) in configuration files.
// Callers may append additional patterns before passing the list to
// ScanFile or GenerateEnvExample.
func DefaultPatterns() []*regexp.Regexp {
	return []*regexp.Regexp{
		// Known token formats — match anywhere in the line.
		regexp.MustCompile(`(?i)ghp_[A-Za-z0-9]{36,}`),                      // GitHub classic PAT
		regexp.MustCompile(`(?i)gh[ps]_[A-Za-z0-9]{36,}`),                   // GitHub fine-grained / installation
		regexp.MustCompile(`(?i)gh[ousr]_[A-Za-z0-9]{36,}`),                 // GitHub OAuth / user / server / refresh tokens
		regexp.MustCompile(`(?i)\bxox[bp]-[A-Za-z0-9-]{10,}\b`),             // Slack bot / user tokens
		regexp.MustCompile(`(?i)\bsk-(?:proj-)?[A-Za-z0-9]{32,}\b`),         // OpenAI project / session keys
		regexp.MustCompile(`(?i)\bsk-ant-(?:api\d{2}-)?[A-Za-z0-9]{32,}\b`), // Anthropic / Claude keys

		// Named key=value / key:value assignments, flexible case/separator.
		regexp.MustCompile(`(?im)^\s*(?:export\s+)?\w*(?:api[_-]?key|apikey|token|secret|password|passwd|pwd|auth)\w*\s*[:=]\s*['"]?\s*\S+`),

		// JSON/YAML style: "apiKey": "sk-..." or apiKey: sk-...
		regexp.MustCompile(`(?i)"?(?:api[_-]?key|apikey|token|secret|password|auth[_-]?token)"?\s*[:=]\s*['"]?\s*\S+`),

		// GitHub token named assignments.
		regexp.MustCompile(`(?i)github[_-]?token\s*[:=]\s*['"]?\s*\S+`),
	}
}

// ScanResult describes a single secret found in a file.
type ScanResult struct {
	FilePath string // absolute path to the file
	Pattern  string // the regex pattern that matched
	Line     int    // 1-based line number
	content  string // the matched line (truncated to 120 chars); unexported to prevent accidental exposure
}

// ScanFile reads a file line by line and reports any lines that match
// one of the supplied secret patterns. Returns an empty slice when
// nothing is found.
func ScanFile(filePath string, patterns []*regexp.Regexp) ([]ScanResult, error) {
	f, err := os.Open(filePath)
	if err != nil {
		return nil, fmt.Errorf("open: %w", err)
	}
	defer func() { _ = f.Close() }()

	var results []ScanResult
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 0, 1024*1024), 1024*1024) // 1 MB max line

	lineNum := 0
	for scanner.Scan() {
		lineNum++
		line := scanner.Text()

		for _, pat := range patterns {
			if pat.MatchString(line) {
				truncated := line
				if len(truncated) > 120 {
					truncated = truncated[:117] + "..."
				}
				results = append(results, ScanResult{
					FilePath: filePath,
					Pattern:  pat.String(),
					Line:     lineNum,
					content:  truncated,
				})
				break // one match per line is enough
			}
		}
	}

	if err := scanner.Err(); err != nil {
		return results, fmt.Errorf("scan: %w", err)
	}

	return results, nil
}

// GenerateEnvExample reads each file path, replaces matched secret
// values with <YOUR_*> placeholders, and writes the result to an
// .env.example file in the output directory. Lines that contain a
// secret are kept but redacted; non-secret lines are preserved as-is.
// Source paths are formatted as home-relative paths in section headers.
// Unreadable source files emit a clean human-readable note without leaking
// absolute filesystem paths or usernames.
func GenerateEnvExample(filePaths []string, patterns []*regexp.Regexp, outputDir string) error {
	var out strings.Builder
	out.WriteString("# Generated by bak — replace placeholders with real values.\n")
	out.WriteString("# https://github.com/danielxxomg/bak-cli\n\n")

	for _, fp := range filePaths {
		displayPath, openPath := resolveSourcePaths(fp)
		fmt.Fprintf(&out, "# ---- %s ----\n", displayPath)

		f, err := os.Open(openPath)
		if err != nil {
			fmt.Fprintf(&out, "# [could not read source file: %s]\n\n", unreadableReason(err))
			continue
		}

		scanRedactedFile(&out, f, patterns)
		out.WriteString("\n")
	}

	examplePath := filepath.Join(outputDir, ".env.example")
	if err := os.WriteFile(examplePath, []byte(out.String()), 0644); err != nil {
		return fmt.Errorf("write .env.example: %w", err)
	}

	return nil
}

// resolveSourcePaths determines the user-facing home-relative display path
// and the system path to open for reading.
func resolveSourcePaths(fp string) (displayPath, openPath string) {
	displayPath = fp
	if !strings.HasPrefix(displayPath, "~/") {
		displayPath = paths.ToCanonical(fp)
		if !strings.HasPrefix(displayPath, "~/") {
			displayPath = filepath.Base(fp)
		}
	}
	openPath = fp
	if strings.HasPrefix(openPath, "~/") {
		if home, err := os.UserHomeDir(); err == nil {
			openPath = paths.FromCanonical(openPath, home)
		}
	}
	return displayPath, openPath
}

// unreadableReason maps an os.Open error to a clean, privacy-preserving explanation.
func unreadableReason(err error) string {
	if os.IsNotExist(err) {
		return "file not found"
	}
	if os.IsPermission(err) {
		return "permission denied"
	}
	return "file unreadable"
}

// scanRedactedFile reads lines from f, replaces detected secrets with placeholders,
// and appends the lines to out.
func scanRedactedFile(out *strings.Builder, f *os.File, patterns []*regexp.Regexp) {
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		matched := false
		for _, pat := range patterns {
			if pat.MatchString(line) {
				matched = true
				line = redactLine(line, pat)
				break
			}
		}
		if matched {
			out.WriteString(line + "  # ⚠ secret detected — replaced\n")
		} else {
			out.WriteString(line + "\n")
		}
	}
	if closeErr := f.Close(); closeErr != nil {
		fmt.Fprintf(out, "# [close error]\n")
	}
	if err := scanner.Err(); err != nil {
		fmt.Fprintf(out, "# [scan error]\n")
	}
}

// redactLine replaces the value portion of a secret assignment with a
// <YOUR_SECRET> placeholder. It handles KEY=VALUE and KEY: VALUE styles.
func redactLine(line string, pat *regexp.Regexp) string {
	idx := pat.FindStringIndex(line)
	if idx == nil {
		return line
	}
	return line[:idx[0]] + "<YOUR_SECRET>" + line[idx[1]:]
}
