// Package backup implements the backup engine, secret scanning,
// and the integration points that wire adapters to CLI commands.
package backup

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/danielxxomg/bak-cli/internal/paths"
)

// DefaultPatterns returns the built-in set of regex patterns used to
// detect secrets (API keys, tokens, passwords) in configuration files.
// Callers may append additional patterns before passing the list to
// ScanFile or GenerateEnvExample.
func DefaultPatterns() []*regexp.Regexp {
	return []*regexp.Regexp{
		// Known token formats — match anywhere in the line.
		regexp.MustCompile(`(?i)ghp_[A-Za-z0-9]{36,}`),                      // GitHub classic PAT
		regexp.MustCompile(`(?i)gh[ps]_[A-Za-z0-9]{36,}`),                   // GitHub fine-grained / installation
		regexp.MustCompile(`(?i)gh[ousr]_[A-Za-z0-9]{36,}`),                 // GitHub OAuth / user / server / refresh tokens
		regexp.MustCompile(`(?i)\bxox[bp]-[A-Za-z0-9-]{10,}\b`),             // Slack bot / user tokens
		regexp.MustCompile(`(?i)\bsk-(?:proj-)?[A-Za-z0-9]{32,}\b`),         // OpenAI project / session keys
		regexp.MustCompile(`(?i)\bsk-ant-(?:api\d{2}-)?[A-Za-z0-9]{32,}\b`), // Anthropic / Claude keys

		// Named key=value / key:value assignments, flexible case/separator.
		regexp.MustCompile(`(?im)^\s*(?:export\s+)?\w*(?:api[_-]?key|apikey|token|secret|password|passwd|pwd|auth)\w*\s*[:=]\s*['"]?\s*\S+`),

		// JSON/YAML style: "apiKey": "sk-..." or apiKey: sk-...
		// Generic key/value secrets. The closing quote belongs outside the
		// alternation (it previously applied only to auth_token) and the value
		// stops at JSON/YAML structure so redacting one secret no longer eats
		// the rest of the line.
		regexp.MustCompile(`(?i)"?(?:api[_-]?key|apikey|token|secret|password|auth[_-]?token)"?\s*[:=]\s*['"]?[^\s'",}]+`),

		// GitHub token named assignments.
		regexp.MustCompile(`(?i)github[_-]?token\s*[:=]\s*['"]?\s*\S+`),

		// AWS access key ID (AKIA long-lived, ASIA temporary/sts).
		regexp.MustCompile(`(?i)\b(?:AKIA|ASIA)[0-9A-Z]{16}\b`),

		// Google Cloud API key.
		regexp.MustCompile(`\bAIza[0-9A-Za-z_-]{35}\b`),

		// Stripe secret keys. Publishable pk_ keys are deliberately NOT matched:
		// Stripe documents them as safe for client-side use, and redacting them would
		// replace working configuration with placeholders on restore.
		regexp.MustCompile(`\b[sr]k_(?:live|test)_[0-9A-Za-z]{10,}\b`),

		// Connection strings carrying inline credentials. A DSN without user:password
		// must not match, so both credential components are required.
		regexp.MustCompile("(?i)\\b(?:postgres(?:ql)?|mysql|mariadb|mongodb(?:\\+srv)?|redis|rediss|amqps?)://[^\\s:@/'\"]+:[^\\s@/'\"]+@[^\\s'\"]+"),

		// HTTP Bearer tokens.
		regexp.MustCompile(`(?i)\bBearer\s+[A-Za-z0-9\-._~+/]{20,}={0,2}`),
	}
}

// ScanResult describes a single secret found in a file.
type ScanResult struct {
	FilePath string // absolute path to the file
	Pattern  string // the regex pattern that matched
	Line     int    // 1-based line number
	content  string // the matched line (truncated to 120 chars); unexported to prevent accidental exposure
}

// ScanFile reads a file line by line and reports any lines that match
// one of the supplied secret patterns. Returns an empty slice when
// nothing is found.
func ScanFile(filePath string, patterns []*regexp.Regexp) ([]ScanResult, error) {
	f, err := os.Open(filePath)
	if err != nil {
		return nil, fmt.Errorf("open: %w", err)
	}
	defer func() { _ = f.Close() }()

	var results []ScanResult
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 0, 1024*1024), 1024*1024) // 1 MB max line

	lineNum := 0
	for scanner.Scan() {
		lineNum++
		line := scanner.Text()

		for _, pat := range patterns {
			if pat.MatchString(line) {
				truncated := line
				if len(truncated) > 120 {
					truncated = truncated[:117] + "..."
				}
				results = append(results, ScanResult{
					FilePath: filePath,
					Pattern:  pat.String(),
					Line:     lineNum,
					content:  truncated,
				})
				break // one match per line is enough
			}
		}
	}

	if err := scanner.Err(); err != nil {
		return results, fmt.Errorf("scan: %w", err)
	}

	return results, nil
}

// GenerateEnvExample reads each file path, replaces matched secret
// values with <YOUR_*> placeholders, and writes the result to an
// .env.example file in the output directory. Lines that contain a
// secret are kept but redacted; non-secret lines are preserved as-is.
// Source paths are formatted as home-relative paths in section headers.
// Unreadable source files emit a clean human-readable note without leaking
// absolute filesystem paths or usernames.
func GenerateEnvExample(filePaths []string, patterns []*regexp.Regexp, outputDir string) error {
	var out strings.Builder
	out.WriteString("# Generated by bak — replace placeholders with real values.\n")
	out.WriteString("# https://github.com/danielxxomg/bak-cli\n\n")

	for _, fp := range filePaths {
		displayPath, openPath := resolveSourcePaths(fp)
		fmt.Fprintf(&out, "# ---- %s ----\n", displayPath)

		f, err := os.Open(openPath)
		if err != nil {
			fmt.Fprintf(&out, "# [could not read source file: %s]\n\n", unreadableReason(err))
			continue
		}

		scanRedactedFile(&out, f, patterns)
		out.WriteString("\n")
	}

	examplePath := filepath.Join(outputDir, ".env.example")
	if err := os.WriteFile(examplePath, []byte(out.String()), 0644); err != nil {
		return fmt.Errorf("write .env.example: %w", err)
	}

	return nil
}

// resolveSourcePaths determines the user-facing home-relative display path
// and the system path to open for reading.
func resolveSourcePaths(fp string) (displayPath, openPath string) {
	displayPath = fp
	if !strings.HasPrefix(displayPath, "~/") {
		displayPath = paths.ToCanonical(fp)
		if !strings.HasPrefix(displayPath, "~/") {
			displayPath = filepath.Base(fp)
		}
	}
	openPath = fp
	if strings.HasPrefix(openPath, "~/") {
		if home, err := os.UserHomeDir(); err == nil {
			openPath = paths.FromCanonical(openPath, home)
		}
	}
	return displayPath, openPath
}

// unreadableReason maps an os.Open error to a clean, privacy-preserving explanation.
func unreadableReason(err error) string {
	if os.IsNotExist(err) {
		return "file not found"
	}
	if os.IsPermission(err) {
		return "permission denied"
	}
	return "file unreadable"
}

// scanRedactedFile reads lines from f, replaces detected secrets with placeholders,
// and appends the lines to out.
func scanRedactedFile(out *strings.Builder, f *os.File, patterns []*regexp.Regexp) {
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		line, matched := redactLine(line, patterns)
		if matched {
			out.WriteString(line + "  # ⚠ secret detected — replaced\n")
		} else {
			out.WriteString(line + "\n")
		}
	}
	if closeErr := f.Close(); closeErr != nil {
		fmt.Fprintf(out, "# [close error]\n")
	}
	if err := scanner.Err(); err != nil {
		fmt.Fprintf(out, "# [scan error]\n")
	}
}

// redactLineCount replaces every secret match on the line with a
// <YOUR_SECRET> placeholder and returns the count of merged secrets replaced.
func redactLineCount(line string, patterns []*regexp.Regexp) (string, int) {
	type span struct{ start, end int }
	var spans []span
	for _, pat := range patterns {
		for _, m := range pat.FindAllStringIndex(line, -1) {
			spans = append(spans, span{m[0], m[1]})
		}
	}
	if len(spans) == 0 {
		return line, 0
	}

	sort.Slice(spans, func(i, j int) bool {
		if spans[i].start == spans[j].start {
			return spans[i].end > spans[j].end
		}
		return spans[i].start < spans[j].start
	})

	merged := []span{spans[0]}
	for _, s := range spans[1:] {
		last := &merged[len(merged)-1]
		if s.start <= last.end {
			if s.end > last.end {
				last.end = s.end
			}
			continue
		}
		merged = append(merged, s)
	}

	var b strings.Builder
	prev := 0
	for _, m := range merged {
		b.WriteString(line[prev:m.start])
		b.WriteString("<YOUR_SECRET>")
		prev = m.end
	}
	b.WriteString(line[prev:])
	return b.String(), len(merged)
}

// redactLine replaces every secret match on the line with a single
// <YOUR_SECRET> placeholder and reports whether anything matched.
//
// All patterns are applied, not just the first one: a single JSON line
// commonly carries several credential families at once, and stopping at the
// first match leaked the others. Matches from every pattern are collected and
// merged before rewriting so overlapping spans cannot corrupt the output or
// shift offsets.
func redactLine(line string, patterns []*regexp.Regexp) (string, bool) {
	redacted, count := redactLineCount(line, patterns)
	return redacted, count > 0
}

// RedactContent redacts secrets from data using patterns, preserving original
// line terminators (CRLF or LF) and whether the file ended with a newline.
// Returns the redacted bytes and the count of replaced secret occurrences.
func RedactContent(data []byte, patterns []*regexp.Regexp) ([]byte, int) {
	if len(data) == 0 {
		return data, 0
	}
	var b strings.Builder
	totalSecrets := 0
	content := string(data)
	for len(content) > 0 {
		idx := strings.IndexByte(content, '\n')
		var line, term string
		if idx >= 0 {
			rawLine := content[:idx]
			content = content[idx+1:]
			if strings.HasSuffix(rawLine, "\r") {
				line = rawLine[:len(rawLine)-1]
				term = "\r\n"
			} else {
				line = rawLine
				term = "\n"
			}
		} else {
			line = content
			content = ""
			term = ""
		}
		redacted, count := redactLineCount(line, patterns)
		totalSecrets += count
		b.WriteString(redacted)
		b.WriteString(term)
	}
	return []byte(b.String()), totalSecrets
}

// RedactFileInPlaceFS redacts secrets in filePath using fsys (or os when nil),
// preserving the file's permission bits. Returns the number of replaced secrets.
func RedactFileInPlaceFS(fsys FS, filePath string, patterns []*regexp.Regexp) (int, error) {
	var (
		data []byte
		perm os.FileMode = 0644
		err  error
	)
	if fsys != nil {
		if info, statErr := fsys.Stat(filePath); statErr == nil {
			perm = info.Mode().Perm()
		}
		data, err = fsys.ReadFile(filePath)
	} else {
		if info, statErr := os.Stat(filePath); statErr == nil {
			perm = info.Mode().Perm()
		}
		data, err = os.ReadFile(filePath)
	}
	if err != nil {
		return 0, fmt.Errorf("read file: %w", err)
	}

	redactedData, count := RedactContent(data, patterns)
	if count == 0 {
		return 0, nil
	}

	cleanPath := filepath.Clean(filePath)
	if fsys != nil {
		if err := fsys.WriteFile(cleanPath, redactedData, perm); err != nil {
			return count, fmt.Errorf("write redacted file: %w", err)
		}
	} else {
		//nolint:gosec // G703: cleanPath is clean path within backup directory
		if err := os.WriteFile(cleanPath, redactedData, perm); err != nil {
			return count, fmt.Errorf("write redacted file: %w", err)
		}
	}
	return count, nil
}

// RedactFileInPlace redacts secrets in filePath in-place, preserving file permissions.
// Returns the count of replaced secrets.
func RedactFileInPlace(filePath string, patterns []*regexp.Regexp) (int, error) {
	return RedactFileInPlaceFS(nil, filePath, patterns)
}
