// Package backup implements the backup engine, secret scanning,
// and the integration points that wire adapters to CLI commands.
package backup

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// DefaultPatterns returns the built-in set of regex patterns used to
// detect secrets (API keys, tokens, passwords) in configuration files.
// Callers may append additional patterns before passing the list to
// ScanFile or GenerateEnvExample.
func DefaultPatterns() []*regexp.Regexp {
	return []*regexp.Regexp{
		// Known token formats — match anywhere in the line.
		regexp.MustCompile(`(?i)ghp_[A-Za-z0-9]{36,}`),                    // GitHub classic PAT
		regexp.MustCompile(`(?i)gh[ps]_[A-Za-z0-9]{36,}`),                  // GitHub fine-grained / installation
		regexp.MustCompile(`(?i)\bsk-(?:proj-)?[A-Za-z0-9]{32,}\b`),        // OpenAI project / session keys
		regexp.MustCompile(`(?i)\bsk-ant-(?:api\d{2}-)?[A-Za-z0-9]{32,}\b`), // Anthropic / Claude keys

		// Named key=value / key:value assignments, flexible case/separator.
		regexp.MustCompile(`(?im)^\s*(?:export\s+)?\w*(?:api[_-]?key|apikey|token|secret|password|passwd|pwd|auth)\w*\s*[:=]\s*['"]?\s*\S+`),

		// JSON/YAML style: "apiKey": "sk-..." or apiKey: sk-...
		regexp.MustCompile(`(?i)"?(?:api[_-]?key|apikey|token|secret|password|auth[_-]?token)"?\s*[:=]\s*['"]?\s*\S+`),

		// GitHub token named assignments.
		regexp.MustCompile(`(?i)github[_-]?token\s*[:=]\s*['"]?\s*\S+`),
	}
}

// ScanResult describes a single secret found in a file.
type ScanResult struct {
	FilePath string // absolute path to the file
	Pattern  string // the regex pattern that matched
	Line     int    // 1-based line number
	Content  string // the matched line (truncated to 120 chars)
}

// ScanFile reads a file line by line and reports any lines that match
// one of the supplied secret patterns. Returns an empty slice when
// nothing is found.
func ScanFile(filePath string, patterns []*regexp.Regexp) ([]ScanResult, error) {
	f, err := os.Open(filePath)
	if err != nil {
		return nil, fmt.Errorf("open: %w", err)
	}
	defer f.Close()

	var results []ScanResult
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 0, 1024*1024), 1024*1024) // 1 MB max line

	lineNum := 0
	for scanner.Scan() {
		lineNum++
		line := scanner.Text()

		for _, pat := range patterns {
			if pat.MatchString(line) {
				truncated := line
				if len(truncated) > 120 {
					truncated = truncated[:117] + "..."
				}
				results = append(results, ScanResult{
					FilePath: filePath,
					Pattern:  pat.String(),
					Line:     lineNum,
					Content:  truncated,
				})
				break // one match per line is enough
			}
		}
	}

	if err := scanner.Err(); err != nil {
		return results, fmt.Errorf("scan: %w", err)
	}

	return results, nil
}

// GenerateEnvExample reads each file path, replaces matched secret
// values with <YOUR_*> placeholders, and writes the result to an
// .env.example file in the output directory. Lines that contain a
// secret are kept but redacted; non-secret lines are preserved as-is.
func GenerateEnvExample(filePaths []string, patterns []*regexp.Regexp, outputDir string) error {
	var out strings.Builder
	out.WriteString("# Generated by bak — replace placeholders with real values.\n")
	out.WriteString("# https://github.com/danielxxomg/bak-cli\n\n")

	for _, fp := range filePaths {
		base := filepath.Base(fp)
		out.WriteString(fmt.Sprintf("# ---- %s ----\n", base))

		f, err := os.Open(fp)
		if err != nil {
			out.WriteString(fmt.Sprintf("# [could not read: %v]\n\n", err))
			continue
		}

		scanner := bufio.NewScanner(f)
		for scanner.Scan() {
			line := scanner.Text()
			matched := false
			for _, pat := range patterns {
				if pat.MatchString(line) {
					matched = true
					// Replace key=value with key=<YOUR_...>
					line = redactLine(line, pat)
					break
				}
			}
			if matched {
				out.WriteString(line + "  # ⚠ secret detected — replaced\n")
			} else {
				out.WriteString(line + "\n")
			}
		}
		f.Close()

		if err := scanner.Err(); err != nil {
			out.WriteString(fmt.Sprintf("# [scan error: %v]\n", err))
		}
		out.WriteString("\n")
	}

	examplePath := filepath.Join(outputDir, ".env.example")
	if err := os.WriteFile(examplePath, []byte(out.String()), 0644); err != nil {
		return fmt.Errorf("write .env.example: %w", err)
	}

	return nil
}

// redactLine replaces the value portion of a secret assignment with a
// placeholder. It handles KEY=VALUE and KEY: VALUE styles.
func redactLine(line string, pat *regexp.Regexp) string {
	// Use the pattern to identify which key was matched, then replace
	// the value portion with a placeholder.

	match := pat.FindStringSubmatch(line)
	if len(match) < 2 {
		// Pattern matched but no capture group — replace the whole value segment.
		idx := pat.FindStringIndex(line)
		if idx == nil {
			return line
		}
		return line[:idx[0]] + "<YOUR_SECRET>" + line[idx[1]:]
	}

	// Replace the captured value with <YOUR_*> placeholder.
	fullMatch := match[0]
	secret := match[1]

	// Derive a meaningful placeholder name from the key pattern.
	placeholder := derivePlaceholder(line, secret)

	return strings.Replace(line, fullMatch, strings.Replace(fullMatch, secret, placeholder, 1), 1)
}

// derivePlaceholder returns a <YOUR_*> placeholder based on the context
// of the secret line (e.g., API_KEY → <YOUR_API_KEY>).
func derivePlaceholder(line, secret string) string {
	lower := strings.ToLower(line)

	switch {
	case strings.Contains(lower, "github") && strings.Contains(lower, "token"):
		return "<YOUR_GITHUB_TOKEN>"
	case strings.Contains(lower, "openai") || strings.Contains(lower, "chatgpt"):
		return "<YOUR_OPENAI_API_KEY>"
	case strings.Contains(lower, "anthropic") || strings.Contains(lower, "claude"):
		return "<YOUR_ANTHROPIC_API_KEY>"
	case strings.Contains(lower, "api_key") || strings.Contains(lower, "apikey"):
		return "<YOUR_API_KEY>"
	case strings.Contains(lower, "token"):
		return "<YOUR_TOKEN>"
	case strings.Contains(lower, "password") || strings.Contains(lower, "passwd") || strings.Contains(lower, "pwd"):
		return "<YOUR_PASSWORD>"
	case strings.Contains(lower, "secret"):
		return "<YOUR_SECRET>"
	default:
		return "<YOUR_SECRET>"
	}
}
